### ISSUE TITLE
Panic: send on closed channel

### ISSUE THREAD

**Issue by flaupretre** [ecadlabs/tezos_exporter#20]
I have been running this exporter as a sidecar to tezos nodes in Kubernetes for some weeks now and I first want to thank you for this great software. Unfortunately, it regulaly crashes and causes its pod to restart. Crash frequency is very variable and different on the different pods I run : some may fail more than 100 times in 24 hours, while others may remain stable during more than one week. Here is the stack trace we get (always the same) : 

level=info msg="tezos_exporter starting..." address=:9489
panic: send on closed channel

goroutine 1457 [running]:
github.com/ecadlabs/tezos_exporter/collector.(*NetworkCollector).Collect.func1(0xc000158200, 0xc8, 0x3ad749ea, 0x939ba0, 0xc000068390)
  /tezos_exporter/collector/network.go:203 +0x142
github.com/ecadlabs/go-tezos.(*RPCClient).Do.func1(0xbf738f97b8a6298c, 0x8865367a2, 0xc52ba0, 0xc000364ff0, 0xc000158200, 0xc0001a6000, 0xc0000c1f28)
  /go/pkg/mod/github.com/ecadlabs/go-tezos@v0.0.0-20190625200831-8c95b123c45f/client.go:150 +0x84
github.com/ecadlabs/go-tezos.(*RPCClient).Do(0xc000364ff0, 0xc000158200, 0x805200, 0xc0002ee420, 0x939ba0, 0xc000068390)
  /go/pkg/mod/github.com/ecadlabs/go-tezos@v0.0.0-20190625200831-8c95b123c45f/client.go:169 +0x1b6
github.com/ecadlabs/go-tezos.(*Service).GetBootstrapped(0xc0001144a8, 0x942c40, 0xc0002ee3c0, 0xc0002ee420, 0x0, 0x0)
  /go/pkg/mod/github.com/ecadlabs/go-tezos@v0.0.0-20190625200831-8c95b123c45f/service.go:517 +0xd8
github.com/ecadlabs/tezos_exporter/collector.getBootstrapped.func1(0xc0001144a8, 0x942c40, 0xc0002ee3c0, 0xc0002ee420, 0xc000140340)
  /tezos_exporter/collector/network.go:149 +0x49
created by github.com/ecadlabs/tezos_exporter/collector.getBootstrapped
  /tezos_exporter/collector/network.go:148 +0x109

      Exit Code:    2

Please tell me if I can help with more information.

**Comment by jevonearth** [comment]
Thank you for the report @flaupretre We will look into it.
