### ISSUE TITLE
Panic when context deadline is exceeded

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/tezos_exporter#7]
```
goroutine 1073 [running]:
github.com/ecadlabs/tezos_exporter/collector.(*NetworkCollector).Collect(0xc420010300, 0xc42005e060)
        /go/src/github.com/ecadlabs/tezos_exporter/collector/network.go:71 +0xe8
github.com/ecadlabs/tezos_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc420198030, 0xc42005e060, 0x85dd00, 0xc420010300)
        /go/src/github.com/ecadlabs/tezos_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:433 +0x61
created by github.com/ecadlabs/tezos_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /go/src/github.com/ecadlabs/tezos_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:431 +0x302
level=warn msg="error querying /network/stat" err="Get http://tezos_node:8732/network/stat: context deadline exceeded"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x73b7a8]
```

**Comment by jevonearth** [comment]
I prefer that the single metric scrape gets skipped, instead of the entire scrape, with a general success/failure metric. 

@juliusv Can you confirm that the general success/failure metric would indicate an error if we have 1 of N metrics fail? That's my reading of the `node_exporter` code you linked.

**Comment by juliusv** [comment]
@jevonearth The node exporter has an error metric per collector module (cpu, filesystem, memory, etc.), not one error metric for the entire scrape. But one collector module can still return multiple metrics. It's then up to the specific collector module to either fail entirely or still return partial metrics (mostly they fail entirely when there's a problem since the metrics come from a single source that can fail, but not all).
